2021-10-13 21:36:47.369864+00:00 __ HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot1232067764:AAH9Y6sts9-rcoLAnAI5CH--jzsUBwRjkGc/getUpdates (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5d3ab39a30>: Failed to establish a new connection: [Errno 101] Сеть недоступна'))
